version: "3.9" 
services:
  nginx:
    container_name: movie-nginx
    depends_on:
      - backend
    restart: always
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: syshero/movie-nginx:1.0.1
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - movie-network

  backend:
    depends_on:
      - mongo
    restart: unless-stopped
    container_name: movie-backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: syshero/movie-backend:1.0.1
    environment:
      - MONGODB_URL=mongodb://mongo:27017/movie
    ports:
      - 5000:5000
    networks:
      - movie-network

  mongo:
    image: mongo:4.4
    container_name: mongodb
    expose:
      - "27017"
    volumes:
      - mongodb:/data/db
    networks:
      - movie-network
      
volumes:
  mongodb: 

networks:
  movie-network:
    driver: bridge
